Update DB

diff --git a/DB b/DB
--- a/DB
+++ b/DB
@@ -1014,6 +1014,13 @@ function ScriptMessage(){
 ## This part is too sensitive.
 #############################################
 #############################################
+ # First thing to do is check if this machine is Debian
+ source /etc/os-release
+if [[ "$ID" != 'ubuntu' ]]; then
+ ScriptMessage
+ echo -e "[\e[1;31mError\e[0m] This script is for ubuntu only, exiting..." 
+ exit 1
+fi
 
  # First thing to do is check if this machine is Debian
  source /etc/os-release
